import { ENEMY_ANT_TUNING } from './antTuning';

export const MAX_UPGRADE_LEVEL = 30;

export const BASE_SPAWN_INTERVAL_SECONDS = 30;
export const MIN_SPAWN_INTERVAL_SECONDS = 7.5;
export const SPAWN_REDUCTION_PER_LEVEL = 0.025;
export const MAX_SPAWN_REDUCTION = 0.75;

export const BASE_MAX_FOOD_ON_FIELD = 14;
export const FOOD_CAPACITY_PER_LEVEL = 2;
export const MAX_FOOD_ON_FIELD = BASE_MAX_FOOD_ON_FIELD + FOOD_CAPACITY_PER_LEVEL * MAX_UPGRADE_LEVEL;

export const BASE_ANT_FORAGE_RADIUS_FACTOR = 0.03;
export const FORAGE_RADIUS_FACTOR_PER_LEVEL = 0.02;
export const MAX_ANT_FORAGE_RADIUS_FACTOR =
  BASE_ANT_FORAGE_RADIUS_FACTOR + FORAGE_RADIUS_FACTOR_PER_LEVEL * MAX_UPGRADE_LEVEL;

export const ANT_SPEED_MULTIPLIER_PER_LEVEL = 0.04;
export const MAX_ANT_SPEED_MULTIPLIER = 2.2;

export const IDLE_COOLDOWN_REDUCTION_PER_LEVEL = 0.015;
export const MIN_IDLE_COOLDOWN_MULTIPLIER = 0.35;

export const PLAYER_NEST_MAX_HEALTH = 100;

export const ENEMY_NEST_INITIAL_COUNT = 2;
export const ENEMY_NEST_BASE_SPAWN_INTERVAL_SECONDS = 20;
export const ENEMY_NEST_MIN_SPAWN_INTERVAL_SECONDS = 6;
export const ENEMY_NEST_SPAWN_INTERVAL_DECAY = 0.95;
export const ENEMY_NEST_XP_PER_SECOND = 1;
export const ENEMY_NEST_BASE_LEVEL_XP = 55;
export const ENEMY_NEST_LEVEL_XP_EXPONENT = 1.35;
export const ENEMY_NEST_BASE_MAX_ACTIVE_ENEMIES = 3;
export const ENEMY_NEST_MAX_ACTIVE_ENEMIES_PER_4_LEVELS = 1;
export const ENEMY_NEST_BASE_HEALTH = 160;
export const ENEMY_NEST_HEALTH_PER_LEVEL = 16;

export const ENEMY_ANT_BASE_HEALTH = ENEMY_ANT_TUNING.baseHealth;
export const ENEMY_ANT_BASE_DAMAGE = ENEMY_ANT_TUNING.baseDamage;
export const ENEMY_ANT_BASE_SPEED = ENEMY_ANT_TUNING.baseSpeed;
export const ENEMY_ANT_BASE_ATTACK_COOLDOWN_SECONDS = ENEMY_ANT_TUNING.baseAttackCooldownSeconds;
export const ENEMY_ANT_ATTACK_RANGE = ENEMY_ANT_TUNING.baseAttackRange;
export const ENEMY_ANT_HEALTH_SCALE_PER_LEVEL = ENEMY_ANT_TUNING.healthScalePerLevel;
export const ENEMY_ANT_DAMAGE_SCALE_PER_LEVEL = ENEMY_ANT_TUNING.damageScalePerLevel;
export const ENEMY_ANT_SPEED_SCALE_PER_LEVEL = ENEMY_ANT_TUNING.speedScalePerLevel;

export const NEST_DEFENSE_RANGE = 20;
export const NEST_DEFENSE_DAMAGE_PER_SECOND = 8;

export const BASE_POPULATION_CAPACITY = 100;
export const POPULATION_CAPACITY_PER_LEVEL = 150;
export const MAX_POPULATION_CAPACITY = BASE_POPULATION_CAPACITY + POPULATION_CAPACITY_PER_LEVEL * MAX_UPGRADE_LEVEL;