export const MAX_UPGRADE_LEVEL = 30;

export const BASE_SPAWN_INTERVAL_SECONDS = 30;
export const MIN_SPAWN_INTERVAL_SECONDS = 7.5;
export const SPAWN_REDUCTION_PER_LEVEL = 0.025;
export const MAX_SPAWN_REDUCTION = 0.75;

export const BASE_MAX_FOOD_ON_FIELD = 14;
export const FOOD_CAPACITY_PER_LEVEL = 2;
export const MAX_FOOD_ON_FIELD = BASE_MAX_FOOD_ON_FIELD + FOOD_CAPACITY_PER_LEVEL * MAX_UPGRADE_LEVEL;

export const BASE_ANT_FORAGE_RADIUS_FACTOR = 0.03;
export const FORAGE_RADIUS_FACTOR_PER_LEVEL = 0.02;
export const MAX_ANT_FORAGE_RADIUS_FACTOR =
  BASE_ANT_FORAGE_RADIUS_FACTOR + FORAGE_RADIUS_FACTOR_PER_LEVEL * MAX_UPGRADE_LEVEL;

export const ANT_SPEED_MULTIPLIER_PER_LEVEL = 0.04;
export const MAX_ANT_SPEED_MULTIPLIER = 2.2;

export const IDLE_COOLDOWN_REDUCTION_PER_LEVEL = 0.015;
export const MIN_IDLE_COOLDOWN_MULTIPLIER = 0.35;